import os
from pathlib import Path

# Paths
ROOT_DIR = Path(__file__).resolve().parent.parent
RAW_DATA_DIR = ROOT_DIR / "01_SPENVIS_RAW_DATA"
PHYSICS_DIR = ROOT_DIR / "02_RADBIO_NEURO_001_PHYSICS_LAYER" / "RADBIO_NEURO_001_NOTEBOOK_BUILD"
BIOLOGY_DIR = ROOT_DIR / "03_RADBIO_NEURO_002_BIOLOGY_CALIBRATION"
NEURAL_DIR = ROOT_DIR / "04_RADBIO_NEURO_003_NEURAL_LAYER"
INTEGRATED_DIR = ROOT_DIR / "06_INTEGRATED_PIPELINE"

# Outputs target folders
INT_OUT_DIR = INTEGRATED_DIR / "outputs"
INT_FIG_DIR = INTEGRATED_DIR / "figures"
INT_REP_DIR = INTEGRATED_DIR / "reports"

# Mission constants
MISSION_DAYS = 180.0
